build:
    tests:
      override:
          -
              command: 'phpunit --coverage-clover=clover.xml'
              coverage:
                  file: 'clover.xml'
                  format: 'clover'
    dependencies:
        before:
            - 'sudo apt-get install -y mercurial'
            - 'git config --global user.email "test@test.com"'
            - 'git config --global user.name "John Doe"'

    environment:
      php:
        version: 5.6.3
        ini:
          'phar.readonly': '0'

#tools:
#    external_code_coverage:
#        enabled: false
#
#    php_cpd:
#        enabled: true
#
#    php_hhvm:
#        enabled: true
#        config:
#            use_undeclared_constant:  false
#
#    php_mess_detector:
#        enabled: true
#        config:
#            controversial_rules:
#                superglobals: false
#
#    php_pdepend:
#        enabled: true
#
#    php_analyzer:
#        enabled: false
#
#    php_code_coverage:
#        enabled: false
#
#    php_code_sniffer:
#        enabled: false
#
#    sensiolabs_security_checker:
#        enabled: true

filter:
    excluded_paths:
        - 'bin/*'
        - 'test/*'

checks:
    php:
        code_rating: true
        remove_extra_empty_lines: true
        remove_php_closing_tag: true
        remove_trailing_whitespace: true

coding_style:
    php: {  }